linagora/jmap-dart-client

- LICENSE
This is just like the licensing chosen for https://github.com/linagora/jmap-client-ts
> Adopt the MIT license

- lib/http/converter/individual_header_identifier_converter.dart
- lib/jmap/mail/email/email.dart
- lib/jmap/mail/email/individual_header_identifier.dart
- test/jmap/email/set/set_email_method_test.dart
- test/jmap/email/submission/set_email_submission_method_test.dart
@hoangdat  please review and merge it
> TF-221 Create emails with User-Agent header

- lib/jmap/core/filter/operator/logic_filter_operator.dart
- test/jmap/email/query/query_with_operator_emails_test.dart
create query operator and create query operator email test
> create query operator and create query operator email test

- lib/jmap/mail/email/get/get_email_response.dart
- test/jmap/email/sort_list_email_test.dart
[https://github.com/linagora/tmail-flutter/pull/779](https://github.com/linagora/tmail-flutter/pull/779)
> Fix sort compare list email

- lib/jmap/core/error/method/error_method_response.dart
- lib/jmap/core/error/method/exception/error_method_response_exception.dart
- lib/jmap/core/request/reference_path.dart
- lib/jmap/core/response/response_object.dart
- test/jmap/email/get_list_email_test.dart
- test/jmap/email/query/query_with_operator_emails_test.dart
- test/jmap/email/search/use_case_test/search_by_after_use_case_test.dart
- test/jmap/email/search/use_case_test/search_by_form_use_case_test.dart
- test/jmap/email/search/use_case_test/search_by_time_and_text_use_case_test.dart
- test/jmap/email/search/use_case_test/search_emails_inbox_use_case_test.dart
- test/jmap/email/sort_list_email_test.dart
- test/jmap/mailbox/changes/get_changes_mailbox_test.dart
https://user-images.githubusercontent.com/6462404/191409055-50713239-22d2-4c1b-b1df-09b762134512.mov
https://user-images.githubusercontent.com/6462404/191412315-fccfe12e-d79e-480a-b7fd-aae68167610a.mov
> [Fastmail interoperation] Parsing Error-Method response

- lib/jmap/core/method/response/set_response.dart
- lib/jmap/identities/identity.dart
- lib/jmap/identities/set/set_identity_response.dart
- lib/jmap/mail/email/set/set_email_response.dart
- lib/jmap/mail/email/submission/set/set_email_submission_response.dart
- lib/jmap/mail/mailbox/set/set_mailbox_response.dart
- lib/jmap/mail/vacation/set/set_vacation_response.dart
- `SetResponse` has `newState` null on server `FastMail`
- Tested with `CRUD` identity on `FastMail`
https://user-images.githubusercontent.com/80730648/192410851-ed1bc43c-7fdd-4116-a89b-a93acd19fb82.mov
> Change `newState` in `SetResponse` can take null value

- lib/http/converter/quotas/data_type_converter.dart
- lib/jmap/core/capability/capability_identifier.dart
- lib/jmap/quotas/data_types.dart
- lib/jmap/quotas/get/get_quota_method.dart
- lib/jmap/quotas/get/get_quota_method.g.dart
- lib/jmap/quotas/get/get_quota_response.dart
- lib/jmap/quotas/get/get_quota_response.g.dart
- lib/jmap/quotas/quota.dart
- lib/jmap/quotas/quota.g.dart
- test/jmap/quotas/get_quota_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/1078
> Add method `Quota/get`

- lib/jmap/mail/mailbox/mailbox_filter_condition.dart
- lib/jmap/mail/mailbox/mailbox_filter_condition.g.dart
- lib/jmap/mail/mailbox/query/query_mailbox_method.dart
- lib/jmap/mail/mailbox/query/query_mailbox_response.dart
- lib/jmap/mail/mailbox/query/query_mailbox_response.g.dart
- test/jmap/mailbox/query/query_mailbox_test.dart
TF-1362: Query mailbox with role spam report
> TF-1362: Query mailbox spam report

- .github/workflows/ci.yml
- .github/workflows/test.yml
- pubspec.yaml
- test/jmap/core/session/test_capability.dart
- test/jmap/email/changes/get_changes_email_test.dart
- test/jmap/email/get_list_email_test.dart
- test/jmap/email/query/query_with_operator_emails_test.dart
- test/jmap/email/search/use_case_test/search_by_after_use_case_test.dart
- test/jmap/email/search/use_case_test/search_by_form_use_case_test.dart
- test/jmap/email/search/use_case_test/search_by_time_and_text_use_case_test.dart
- test/jmap/email/search/use_case_test/search_emails_inbox_use_case_test.dart
- test/jmap/email/set/set_email_method_test.dart
- test/jmap/email/sort_list_email_test.dart
- test/jmap/email/submission/set_email_submission_method_test.dart
- test/jmap/identities/create_identity_with_sort_order_test.dart
- test/jmap/identities/get_identities_with_sort_order_test.dart
- test/jmap/identities/get_identity_method_test.dart
- test/jmap/identities/set_identity_method_test.dart
- test/jmap/mailbox/changes/get_changes_mailbox_test.dart
- test/jmap/mailbox/get/get_mailbox_method_test.dart
- test/jmap/mailbox/query/query_mailbox_test.dart
- test/jmap/mailbox/set/set_mailbox_method_test.dart
- test/jmap/mdn/send/mdn_send_method_test.dart
- test/jmap/push/get_push_subscription_method_test.dart
- test/jmap/push/set_push_subscription_method_test.dart
- test/jmap/quotas/get_quota_method_test.dart
- test/jmap/vacation/get_vacation_method_test.dart
- test/jmap/vacation/set_vacation_method_test.dart
> Upgrade flutter version to `v3.7.5`

- lib/jmap/mail/email/email.dart
- test/jmap/email/changes/get_changes_email_test.dart
- test/jmap/email/get_list_email_test.dart
- test/jmap/email/query/query_with_operator_emails_test.dart
- test/jmap/email/search/use_case_test/search_by_after_use_case_test.dart
- test/jmap/email/search/use_case_test/search_by_form_use_case_test.dart
- test/jmap/email/search/use_case_test/search_by_time_and_text_use_case_test.dart
- test/jmap/email/search/use_case_test/search_emails_inbox_use_case_test.dart
- test/jmap/email/set/set_email_method_test.dart
- test/jmap/email/sort_list_email_test.dart
- test/jmap/email/submission/set_email_submission_method_test.dart
> Support for `CYRUS`

- lib/jmap/core/method/request/parse_method.dart
- lib/jmap/core/method/response/parse_response.dart
- lib/jmap/mail/calendar/parse/calendar_event_parse_method.dart
- lib/jmap/mail/calendar/parse/calendar_event_parse_response.dart
- test/jmap/calendar/calendar_event_parse_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/1775
> Add calendar event parse method

- lib/jmap/mail/email/email.dart
- lib/jmap/mail/email/individual_header_identifier.dart
- test/jmap/email/get/get_email_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/1857
> Add header calendar event property to email

- lib/jmap/quotas/quota.dart
- lib/jmap/quotas/quota.g.dart
- test/jmap/quotas/get_quota_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/2063
> Add `types` property for Quota object

- lib/jmap/core/method/request/calendar_event_reply_method.dart
- lib/jmap/core/method/response/calendar_event_reply_response.dart
- lib/jmap/mail/calendar/reply/calendar_event_accept_method.dart
- lib/jmap/mail/calendar/reply/calendar_event_accept_method.g.dart
- lib/jmap/mail/calendar/reply/calendar_event_accept_response.dart
- lib/util/json_parsers.dart
- test/jmap/mail/calendar/reply/calendar_event_accept_method_test.dart
- test/util/json_parsers_test.dart
- https://github.com/linagora/tmail-flutter/issues/2425
> Create CalendarEvent accept method

- lib/jmap/mail/calendar/reply/calendar_event_reject_method.dart
- lib/jmap/mail/calendar/reply/calendar_event_reject_method.g.dart
- lib/jmap/mail/calendar/reply/calendar_event_reject_response.dart
- test/jmap/mail/calendar/reply/calendar_event_reject_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/2425
> Create calendar event reject method

- lib/http/converter/capabilities_converter.dart
- lib/jmap/core/capability/calendar_event_capability.dart
- lib/jmap/core/capability/calendar_event_capability.g.dart
- test/jmap/core/session/session_test.dart
- https://github.com/linagora/tmail-flutter/issues/2859
> Add calendar event capability properties

- .github/workflows/ci.yml
- lib/http/converter/identities/public_asset_identities_converter.dart
- lib/jmap/core/capability/capability_identifier.dart
- lib/jmap/core/error/set_error.dart
- lib/jmap/core/patch_object.dart
- lib/jmap/mail/extensions/public_asset/get/get_public_asset_method.dart
- lib/jmap/mail/extensions/public_asset/get/get_public_asset_method.g.dart
- lib/jmap/mail/extensions/public_asset/get/get_public_asset_response.dart
- lib/jmap/mail/extensions/public_asset/get/get_public_asset_response.g.dart
- lib/jmap/mail/extensions/public_asset/public_asset.dart
- lib/jmap/mail/extensions/public_asset/public_asset.g.dart
- lib/jmap/mail/extensions/public_asset/set/set_public_asset_method.dart
- lib/jmap/mail/extensions/public_asset/set/set_public_asset_response.dart
- test/jmap/mail/extensions/public_asset/get/get_public_asset_method_test.dart
- test/jmap/mail/extensions/public_asset/set/set_public_asset_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/2932
- https://github.com/linagora/tmail-flutter/issues/3040
> Implement get and set methods of PublicAsset extension

- lib/jmap/core/error/method/error_method_response.dart
- https://github.com/linagora/tmail-flutter/issues/3096
> Add over quota error type

- CHANGELOG.md
- lib/http/converter/capabilities_converter.dart
- lib/jmap/core/capability/capability_identifier.dart
- lib/jmap/core/capability/web_socket_ticket_capability.dart
- lib/jmap/core/capability/web_socket_ticket_capability.g.dart
- pubspec.yaml
- test/jmap/core/session/session_test.dart
- https://github.com/linagora/tmail-flutter/issues/3156
> Add web socket ticket capability

- lib/jmap/mail/email/search_snippet/search_snippet.dart
- lib/jmap/mail/email/search_snippet/search_snippet.g.dart
- lib/jmap/mail/email/search_snippet/search_snippet_get_method.dart
- lib/jmap/mail/email/search_snippet/search_snippet_get_response.dart
- lib/jmap/mail/email/search_snippet/search_snippet_get_response.g.dart
- test/jmap/mail/email/search_snippet/search_snippet_get_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/3234
> [SearchSnippet][Part-1] Implement SearchSnippet/get

- lib/jmap/core/method/request/set_method.dart
- lib/jmap/mail/email/set/set_email_method.dart
- test/jmap/email/empty_mailbox_test.dart
Related: https://github.com/linagora/tmail-flutter/pull/3372
> TF-3372 Support Reference Destroy to reduce JMAP requests

- lib/http/converter/set_error_converter.dart
- lib/jmap/core/capability/calendar_event_capability.dart
- lib/jmap/core/capability/calendar_event_capability.g.dart
- lib/jmap/mail/calendar/attendance/calendar_event_attendance.dart
- lib/jmap/mail/calendar/attendance/calendar_event_attendance.g.dart
- lib/jmap/mail/calendar/attendance/get_calendar_event_attendance_method.dart
- lib/jmap/mail/calendar/attendance/get_calendar_event_attendance_method.g.dart
- lib/jmap/mail/calendar/attendance/get_calendar_event_attendance_response.dart
- lib/jmap/mail/calendar/attendance/get_calendar_event_attendance_response.g.dart
- test/jmap/mail/calendar/attendance/get_calendar_event_attendance_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/3576
> Add CalendarEventAttendance/get method

- lib/jmap/core/capability/calendar_event_capability.dart
- lib/jmap/core/capability/calendar_event_capability.g.dart
- lib/jmap/mail/calendar/reply/calendar_event_counter_accept_method.dart
- lib/jmap/mail/calendar/reply/calendar_event_counter_accept_method.g.dart
- test/jmap/core/session/session_test.dart
- test/jmap/mail/calendar/reply/calendar_event_counter_accept_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/3590
> Add CalendarEventCounter/accept method

- lib/jmap/thread/get/get_thread_method.dart
- lib/jmap/thread/get/get_thread_method.g.dart
- lib/jmap/thread/get/get_thread_response.dart
- lib/jmap/thread/get/get_thread_response.g.dart
- lib/jmap/thread/thread.dart
- lib/jmap/thread/thread.g.dart
- test/jmap/thread/get/get_thread_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/3638
> Add Thread/get method

- lib/jmap/core/capability/capability_identifier.dart
- lib/jmap/core/error/set_error.dart
- lib/jmap/core/method/request/clear_method.dart
- lib/jmap/core/method/response/clear_response.dart
- lib/jmap/mail/mailbox/clear/clear_mailbox_method.dart
- lib/jmap/mail/mailbox/clear/clear_mailbox_method.g.dart
- lib/jmap/mail/mailbox/clear/clear_mailbox_response.dart
- lib/jmap/mail/mailbox/clear/clear_mailbox_response.g.dart
- pubspec.yaml
- test/jmap/mailbox/clear/clear_mailbox_method_test.dart
[jmap-extensions/mailboxClear.adoc](https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/mailboxClear.adoc)
> Support `Mailbox/clear` method

- lib/jmap/mail/email/email.dart
- lib/jmap/mail/email/individual_header_identifier.dart
- test/jmap/email/set/set_email_method_test.dart
- https://github.com/linagora/tmail-flutter/issues/3786
> Add Return-Path header
